### ISSUE TITLE
error code 261: Application cannot perform write actions

### ISSUE THREAD

**Issue by alxcnwy** [saadmanrafat/twitivity#6]
**Describe the bug**
Getting the following error when I run configure.py - I've set all my credentials correctly I believe.
```
{'errors': [{'code': 261, 'message': 'Application cannot perform write actions. Contact Twitter Platform Operations through https://help.twitter.com/forms/platform.'}]}
<Response [403]>
```

**To Reproduce**
1. Run `python configure.py`

**Expected behavior**
Should work like the demo gif

**Comment by saadmanrafat** [comment]
The Application doesn't have proper permission levels. Please recheck your Twitter App Dashboard settings. You can read more about [error 261](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/subscribe-account-activity/faq) on Twitter Docs.

**Comment by alxcnwy** [comment]
I changed something and am now getting error code 200 Forbidden 😅

**Comment by saadmanrafat** [comment]
Error 200 forbidden is probably because of an incorrect URI. Recheck the URL and make sure you are using HTTPs. The tokens also need to be regenerated after application permissions are changed. Depending on your OS, [set environment variables accordingly to the README.md ](https://github.com/saadmanrafat/twitivity#store-the-credentials-as-environment-variables). And for [Registration and Subscription](https://github.com/saadmanrafat/twitivity#register--subscribe), run these programs in parallel -- [stream_events.py](https://github.com/saadmanrafat/twitivity/blob/master/examples/stream_events.py) and then [configure.py](https://github.com/saadmanrafat/twitivity/blob/master/examples/configure.py). 

We are working on making this more user-friendly, short-circuiting the part where users have to run two different programs in parallel to subscribe to events. Next version will be released in a week or so. In the meantime, I'm happy to answer [anymore  queries you might have](https://twitter.com/saadmanrafat_).

Thanks!

**Comment by alxcnwy** [comment]
I think I followed the instructions correctly but I think I'm being a noob. I already reached out on Twitter but haven't heard back. I also emailed you - looking forward to hearing back - would really appreciate your help! :)

**Comment by saadmanrafat** [comment]
Unfortunately ended up in the junk folder. I replied back!
